# Generated by Django 6.1.1 on 2026-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=512)),
                ("city", models.CharField(db_index=True, max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.PositiveIntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=4, max_digits=8)),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
                (
                    "geocode_source",
                    models.CharField(blank=True, default="", max_length=32),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "city"], name="fuelroute_f_state_5dd587_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuelroute_f_latitud_24ebfc_idx",
                    ),
                    models.Index(
                        fields=["retail_price"], name="fuelroute_f_retail__70ff7d_idx"
                    ),
                ],
            },
        ),
    ]
